title: Janai Ford's Portfolio

plugins:
  - jekyll-bookshop
  - jekyll-sitemap
  - jekyll/tagging

bookshop_locations:
  - ../component-library

sass:
  load_paths:
    - ../component-library/shared/styles
    - ../component-library/components

exclude:
  - postcss.config.js
  - node_modules

include:
  - _cloudcannon

collections_dir: collections

collections:
  pages:
    output: true
    permalink: /:title/
  projects:
    output: true
    permalink: /project/:slug
  testimonials:
    output: false
  posts:
    output: true
    permalink: /blog/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: default

  - scope:
      type: pages
      path: _pages/index.html
    values:
      permalink: /

  - scope:
      type: projects
    values:
      layout: project

  - scope:
      type: posts
    values:
      layout: post

# Tag settings
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: /:title
